set -gq allow-passthrough on
set -g visual-activity off
set -g set-clipboard on
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g status-style bg=#f0a4d0,fg=#000000
